apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-build
spec:
  params:
    - name: username
      type: string
    - name: checkout-url
      type: string
    - name: checkout-revision
      type: string    
    - name: deploy-dst
      type: string    
    - name: deploy-ctx
      type: string          
    - name: deploy-containerFile
      type: string          
    - name: tag-src
      type: string    
    - name: tag-dst
      type: string    
  workspaces:
    - name: shared-data
      description: volume compartilhado.        
  tasks:
    - name: print
      taskRef:
        name: echo
      params:
      - name: mensagem
        value: |
          params.username: $(params.username)
          params.checkout-url: $(params.checkout-url)
          params.checkout-revision: $(params.checkout-revision)
          params.deploy-ctx: $(params.deploy-ctx)
          params.deploy-dst: $(params.deploy-dst)
          params.deploy-containerFile: $(params.deploy-containerFile)          
          params.tag-src: $(params.tag-src)
          params.tag-dst: $(params.tag-dst)
    - name: checkout
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      runAfter:
        - print
      params:
      - name: url
        value: $(params.checkout-url)
      - name: revision
        value: $(params.checkout-revision)
    - name: build
      runAfter:
        - checkout
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
      - name: source
        workspace: shared-data
      params:
      - name: IMAGE
        value: $(params.deploy-dst)
      - name: CONTEXT
        value: $(params.deploy-ctx)
      - name: DOCKERFILE
        value: $(params.deploy-containerFile)          
    - name: tag
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
      - name: images-url
        workspace: shared-data
      params:
      - name: srcImageURL
        value: $(params.tag-src)
      - name: destImageURL
        value: $(params.tag-dst)
