apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-read
spec:
  description: | 
    This pipeline clones a git repo, then echoes the README file to the stdout.
  params:
  - name: git-repo-url
    type: string
    description: The git repo URL to clone from.  
  - name: git-subdirectory
    type: string
    description: The 'workspace-source' git-clone directory target.
  - name: buildah-image
    type: string
  - name: buildah-Containerfile
    type: string
  - name: buildah-contextDir
    type: string
  - name: tag-src
    type: string
  - name: tag-dst
    type: string
  workspaces:
  - name: shared-data
    description: | 
      This workspace contains the cloned repo files, so they can be read by the
      next task.
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.git-repo-url)
    - name: subdirectory
      value: $(params.git-subdirectory)
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    runAfter: 
      - fetch-source
    workspaces:
    - name: source
      workspace: shared-data
    params: 
      - name: IMAGE
        value: $(params.buildah-image)
      - name: DOCKERFILE
        value: $(params.buildah-Containerfile)
      - name: CONTEXT
        value: $(params.buildah-contextDir)
  - name: tag-latest
    taskRef: 
      name: skopeo-copy
      kind: ClusterTask
    runAfter: 
      - build-image
    params:
      - name: srcImageURL
        value: $(params.tag-src)
      - name: destImageURL
        value: $(params.tag-dst)
